version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ecommerce-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ecommerce-net

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - ecommerce-net

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    networks:
      - ecommerce-net

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ecommerce-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - ecommerce-net

  orders.api:
    build:
      context: .
      dockerfile: services/Orders.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - kafka
      - mongo
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - ecommerce-net

  orders.consumer:
    build:
      context: .
      dockerfile: services/Orders.Consumer/Dockerfile
    depends_on:
      - kafka
      - mongo
    environment:
      - DOTNET_ENVIRONMENT=Development
    networks:
      - ecommerce-net

volumes:
  grafana-data:

networks:
  ecommerce-net:
    driver: bridge