global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'orders-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['orders.api:5100']
        labels:
          service: 'orders-api'
          env: 'dev'
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]