global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orders-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['orders.api:80']

  - job_name: 'orders-consumer'
    metrics_path: /metrics
    static_configs:
      - targets: ['orders.consumer:80']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']