name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build & Test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ecommerce-microservices-observability-platform

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ecommerce-microservices-observability-platform

      - name: Build
        run: dotnet build --no-restore --configuration Debug
        working-directory: ecommerce-microservices-observability-platform

      - name: Test with coverage
        run: dotnet test --no-build --configuration Debug --collect:"XPlat Code Coverage"
        working-directory: ecommerce-microservices-observability-platform

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.25
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline_AzurePipelines'

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ecommerce-microservices-observability-platform/coveragereport
